modLoader="javafml"
loaderVersion="[20,)"
license="Not specified"

[[mods]]
modId="create__automation"
displayName="Create: Automation"
version="0.1.0"
description='''

'''
[[dependencies.create__automation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
